#!/usr/bin/env bash
#
# setup_rhel_hosts.sh — Two-box lab: RHEL QA (discovery) + RHEL prod.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ANSIBLE_DIR="${PROJECT_ROOT}/ansible"

DEV_HOST=""
PROD_HOST=""
ANSIBLE_USER="${ANSIBLE_SSH_USER:-ansible}"
DEV_CHECKOUT=""
DEV_INVENTORY="${ANSIBLE_DIR}/inventory.dev.yml"
PROD_INVENTORY="${ANSIBLE_DIR}/inventory.production.yml"

usage() {
    cat <<EOF
Usage: $(basename "$0") <subcommand> [options]

Two RHEL boxes is the default lab: one **QA** (AVC discovery / generate) and
one **prod** (canary → soak → enforce). See docs/demo/203-RHEL_TWO_HOST.md.

Subcommands:
  write     Write ansible/inventory.dev.yml (QA host rhel-qa) and inventory.production.yml
  ping      ansible ping both inventories
  doctor    getenforce / ausearch / sesearch on each host
  bootstrap Print SSH commands to install shopapi on the QA box

write options:
  --qa-host HOST      QA / discovery box IP or DNS (required; alias: --dev-host)
  --dev-host HOST     Same as --qa-host (legacy name)
  --prod-host HOST    Prod box IP or DNS (required)
  --user NAME         SSH user (default: ansible, or ANSIBLE_SSH_USER)
  --qa-checkout PATH  Repo on the QA box (default: /home/<user>/selinux-pac)
  --dev-checkout PATH Same as --qa-checkout (legacy name)

Examples:
  bash scripts/setup_rhel_hosts.sh write --qa-host 10.0.0.10 --prod-host 10.0.0.20
  bash scripts/setup_rhel_hosts.sh ping
  bash scripts/setup_rhel_hosts.sh doctor
  bash scripts/setup_rhel_hosts.sh bootstrap
EOF
}

require_write_args() {
    if [[ -z "${DEV_HOST}" || -z "${PROD_HOST}" ]]; then
        echo "write requires --qa-host (or --dev-host) and --prod-host" >&2
        usage
        exit 2
    fi
}

write_inventories() {
    require_write_args
    local checkout="${DEV_CHECKOUT:-/home/${ANSIBLE_USER}/selinux-pac}"
    cat >"${DEV_INVENTORY}" <<EOF
# Generated by scripts/setup_rhel_hosts.sh — not for git.
# QA RHEL: policy discovery. File name inventory.dev.yml is legacy. soak_min_days=0 is lab-only.
#
# Controller-only (laptop / AAP): policy_artifact_dir, policy_pp_src.
# On rhel-qa after clone + demo_bootstrap.sh --shopapi-only: selinux_ops_dir, app_manifest_path.
# Do not point those two at playbook_dir — that is a Mac/AAP path.

all:
  hosts:
    rhel-qa:
      ansible_host: ${DEV_HOST}
      ansible_user: ${ANSIBLE_USER}
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
  vars:
    app_name: shopapi
    domain: shopapi_t
    install_root: /opt/shopapi
    var_dir: /var/lib/shopapi
    log_dir: /var/log/shopapi
    runtime_dir: /run/shopapi
    service_name: shopapi.service
    selinux_ops_from_package: false
    selinux_ops_dir: ${checkout}/scripts
    policy_artifact_dir: "{{ playbook_dir }}/.."
    policy_pp_src: "{{ policy_artifact_dir }}/selinux/shopapi/shopapi.pp"
    app_manifest_path: ${checkout}/config/shopapi.manifest.yml
    ansible_env_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    soak_marker_file: "/var/lib/selinux-policy-ops/{{ app_name }}/selinux_canary_deployed_at"
    soak_min_days: 0
    soak_max_avc: 0
    soak_max_net_new: 0
    soak_use_net_new: true
    http_probe_host: "127.0.0.1"
EOF

    cat >"${PROD_INVENTORY}" <<EOF
# Generated by scripts/setup_rhel_hosts.sh — not for git.
# Prod RHEL: canary + production groups are the same host.

all:
  children:
    canary:
      hosts:
        rhel-prod:
    production:
      hosts:
        rhel-prod:
  hosts:
    rhel-prod:
      ansible_host: ${PROD_HOST}
      ansible_user: ${ANSIBLE_USER}
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
  vars:
    app_name: shopapi
    domain: shopapi_t
    install_root: /opt/shopapi
    var_dir: /var/lib/shopapi
    log_dir: /var/log/shopapi
    runtime_dir: /run/shopapi
    service_name: shopapi.service
    selinux_ops_from_package: true
    selinux_ops_dir: /usr/libexec/selinux-policy-ops
    app_manifest_path: /etc/shopapi/selinux-manifest.yml
    policy_artifact_dir: "{{ playbook_dir }}/.."
    policy_pp_src: ""
    ansible_env_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    soak_marker_file: "/var/lib/selinux-policy-ops/{{ app_name }}/selinux_canary_deployed_at"
    soak_min_days: 7
    soak_max_avc: 0
    soak_max_net_new: 0
    soak_use_net_new: true
    rollback_dnf_version: ""
    http_probe_host: "127.0.0.1"
EOF

    echo "Wrote ${DEV_INVENTORY} (qa=${DEV_HOST}, host rhel-qa)"
    echo "Wrote ${PROD_INVENTORY} (prod=${PROD_HOST})"
    echo "NOTE: inventory.dev.yml has soak_min_days: 0 (lab only). Do not copy that onto prod."
    echo "Next: bash scripts/setup_rhel_hosts.sh ping"
}

require_inventories() {
    if [[ ! -f "${DEV_INVENTORY}" || ! -f "${PROD_INVENTORY}" ]]; then
        echo "Missing inventories. Run: bash scripts/setup_rhel_hosts.sh write --qa-host … --prod-host …" >&2
        exit 1
    fi
}

require_ansible() {
    if ! command -v ansible >/dev/null 2>&1; then
        echo "ansible not found on this controller. pip install ansible" >&2
        exit 1
    fi
}

ping_hosts() {
    require_inventories
    require_ansible
    echo "=== ping qa ==="
    ansible -i "${DEV_INVENTORY}" all -m ping
    echo "=== ping prod ==="
    ansible -i "${PROD_INVENTORY}" all -m ping
}

doctor_hosts() {
    require_inventories
    require_ansible
    echo "=== doctor qa ==="
    ansible -i "${DEV_INVENTORY}" all -b -m shell -a 'hostname; getenforce; command -v ausearch; command -v sesearch'
    echo "=== doctor prod ==="
    # rpm -q returns 1 when the package is absent. That is expected before canary RPMs.
    ansible -i "${PROD_INVENTORY}" all -b -m shell -a 'hostname; getenforce; command -v ausearch; command -v sesearch; if rpm -q selinux-policy-ops >/dev/null 2>&1; then rpm -q selinux-policy-ops; else echo "selinux-policy-ops: not installed (expected before RPMs)"; fi'
}

print_bootstrap() {
    local dev_hint="rhel-qa.example.com"
    if [[ -f "${DEV_INVENTORY}" ]]; then
        dev_hint="$(awk '/ansible_host:/ { print $2; exit }' "${DEV_INVENTORY}" | tr -d '"')"
        [[ -n "${dev_hint}" ]] || dev_hint="rhel-qa.example.com"
    fi
    cat <<EOF
=== Bootstrap the QA RHEL box (run over SSH as a user with sudo) ===
=== Next: docs/demo/203-RHEL_TWO_HOST.md (look at the prompt: Mac vs rhel-qa) ===

ssh ${ANSIBLE_USER}@${dev_hint}
sudo dnf install -y git java-17-openjdk-headless maven python3 python3-pyyaml \\
  policycoreutils policycoreutils-python-utils setools-console audit selinux-policy-devel
# Clone this repo on the box (or rsync from your laptop):
git clone https://github.com/anurag-saran/selinux-pac.git ~/selinux-pac
cd ~/selinux-pac
# Spring Boot shopapi + types-only seed (SELinuxContext=shopapi_t, permissive).
# Do not curl /feature-spool yet.
sudo bash scripts/demo_bootstrap.sh --shopapi-only
sudo bash scripts/selinux_pac_adopt.sh doctor

Generate on rhel-qa from first-ship AVCs into selinux/shopapi/, copy sources + .pp back,
open a GitHub PR on selinux-pac, then canary from the controller:
  ssh ${ANSIBLE_USER}@${dev_hint} 'cd ~/selinux-pac && sudo bash scripts/dev_generate_policy.sh --apply --allow-needs-review --app-name shopapi --app-root ~/selinux-pac && POLICY_MODULE=shopapi SELINUX_DOMAIN=shopapi_t bash scripts/compile_and_validate.sh ~/selinux-pac/selinux/shopapi'
  scp ${ANSIBLE_USER}@${dev_hint}:~/selinux-pac/selinux/shopapi/shopapi.te ${ANSIBLE_USER}@${dev_hint}:~/selinux-pac/selinux/shopapi/shopapi.fc ${ANSIBLE_USER}@${dev_hint}:~/selinux-pac/selinux/shopapi/policy_version.txt ${ANSIBLE_USER}@${dev_hint}:~/selinux-pac/selinux/shopapi/shopapi.pp selinux/shopapi/
  bash scripts/demo_open_generated_pr.sh
  ansible-playbook -i ansible/inventory.dev.yml ansible/deploy_canary.yml

=== PROD RHEL box (no git clone) ===
=== Explained in docs/demo/203-RHEL_TWO_HOST.md ===

# App first (scp demo/shopapi + demo_bootstrap.sh --shopapi-only --no-seed --unconfined).
# Then RPMs for policy.
sudo dnf install -y java-17-openjdk-headless python3 python3-pyyaml \\
  policycoreutils policycoreutils-python-utils setools-console audit
# After you build RPMs on the controller (or rhel-qa):
#   bash packaging/build_rpms.sh
# Install selinux-policy-ops + shopapi-selinux from your internal repo, then:
  ansible-playbook -i ansible/inventory.production.yml ansible/deploy_canary.yml --limit canary
  ansible-playbook -i ansible/inventory.production.yml ansible/soak_monitor.yml --limit canary
# Customer prod waits 7 days. Talk-only: add -e force_enforce=true (still needs a ticket).
  ansible-playbook -i ansible/inventory.production.yml ansible/enforce_production.yml \\
    -e change_ticket=DEMO -e force_enforce=true

Docs: docs/demo/203-RHEL_TWO_HOST.md
EOF
}

parse_write_opts() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --qa-host|--dev-host) DEV_HOST="$2"; shift 2 ;;
            --prod-host) PROD_HOST="$2"; shift 2 ;;
            --user) ANSIBLE_USER="$2"; shift 2 ;;
            --qa-checkout|--dev-checkout) DEV_CHECKOUT="$2"; shift 2 ;;
            -h|--help) usage; exit 0 ;;
            *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
        esac
    done
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

SUB="$1"
shift

case "${SUB}" in
    write) parse_write_opts "$@"; write_inventories ;;
    ping) ping_hosts ;;
    doctor) doctor_hosts ;;
    bootstrap) print_bootstrap ;;
    -h|--help) usage ;;
    *) echo "Unknown subcommand: ${SUB}" >&2; usage; exit 2 ;;
esac
